### ISSUE TITLE
It does not work on iOS 14

### ISSUE THREAD

**Issue by newbision** [karthiksaral/Sign-In-with-Apple#1]
I cloned your repository and tried to sign in with my apple account. It worked well on iOS 13, but it does not work on iOS 14. Would you please check it and let me know if you find the solution? Thanks

**Comment by karthiksaral** [comment]
what was the issue u faced

**Comment by newbision** [comment]
Would you please check the following screenshot? I typed the password and tapped the continue button, but it does not work on iPhone 12 Pro Max emulators(iOS 14). This code worked well on iOS 13. I am not sure why it does not work on iOS 14. Would you please check it and let me know how to resolve it? Thanks
![Screenshot at Nov 18 10-04-39](https://user-images.githubusercontent.com/14179316/99547853-061f4080-2986-11eb-8f9d-cbff4d1cde5d.png)
